[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'No build step required for backend service'"]

[start]
cmd = "npm run start --workspace=backend"
