[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = [
  "node railway-cleanup.js",
  "npm install --no-audit --progress=false --ignore-scripts --omit=optional",
  "cd backend && npm install --no-audit --progress=false --ignore-scripts"
]

[phases.build]
cmds = ["cd backend && npm run build --if-present"]

[start]
cmd = "npm start"
